import type { ParentCategory, ParentCategoryCode } from '@/types'

export const INCOME_CATEGORIES: Record<ParentCategoryCode, ParentCategory> = {
  INC: {
    code: 'INC',
    label: 'Income',
    subcategories: {
      INC_01: { code: 'INC_01', label: 'Salary & Wages' },
      INC_02: { code: 'INC_02', label: 'Freelance & Self-Employment' },
      INC_03: { code: 'INC_03', label: 'Rental Income' },
      INC_04: { code: 'INC_04', label: 'Investment Income' },
      INC_05: { code: 'INC_05', label: 'Capital Gains' },
      INC_06: { code: 'INC_06', label: 'Government Benefits' },
      INC_07: { code: 'INC_07', label: 'Pension & Retirement' },
      INC_08: { code: 'INC_08', label: 'Tax Refund' },
      INC_09: { code: 'INC_09', label: 'Gifts & Informal Transfers' },
      INC_10: { code: 'INC_10', label: 'Business Revenue' }, // Revenue
      INC_11: { code: 'INC_11', label: 'Side Income & Resale' },
      INC_12: { code: 'INC_12', label: 'Other Income' },
      INC_13: { code: 'INC_13', label: 'Internal Transfer' }, // Matches TFR_02
      FIN_06: { code: 'INC_14', label: 'Interest' },
    },
  },
}

export const EXPENSE_CATEGORIES: Record<ParentCategoryCode, ParentCategory> = {
  HOU: {
    code: 'HOU',
    label: 'Housing & Utilities',
    subcategories: {
      HOU_01: { code: 'HOU_01', label: 'Rent' }, // Office & Rent
      HOU_02: { code: 'HOU_02', label: 'Mortgage' },
      HOU_03: { code: 'HOU_03', label: 'Property Rates & Municipal Fees' },
      HOU_04: { code: 'HOU_04', label: 'Electricity' },
      HOU_05: { code: 'HOU_05', label: 'Gas & Heating' },
      HOU_06: { code: 'HOU_06', label: 'Water & Sewage' },
      HOU_07: { code: 'HOU_07', label: 'Waste & Recycling' },
      HOU_08: { code: 'HOU_08', label: 'Home Internet & Landline' },
      HOU_09: { code: 'HOU_09', label: 'TV Licence & Broadcast Fees' },
      HOU_10: { code: 'HOU_10', label: 'Furniture & Home Furnishings' },
      HOU_11: { code: 'HOU_11', label: 'Home Appliances' },
      HOU_12: { code: 'HOU_12', label: 'Home Improvement & Renovation' },
      HOU_13: { code: 'HOU_13', label: 'Garden & Outdoor' },
      HOU_14: { code: 'HOU_14', label: 'Cleaning & Domestic Services' },
      HOU_15: { code: 'HOU_15', label: 'Security & Alarm Systems' },
      HOU_16: { code: 'HOU_16', label: 'Household Supplies & Hardware' },
      HOU_17: { code: 'HOU_17', label: 'Removal & Storage' },
    },
  },
  GRO: {
    code: 'GRO',
    label: 'Groceries & Daily Essentials',
    subcategories: {
      GRO_01: { code: 'GRO_01', label: 'Supermarket & Grocery' },
      GRO_02: { code: 'GRO_02', label: 'Discount Grocery' },
      GRO_03: { code: 'GRO_03', label: 'Organic & Specialty Food' },
      GRO_04: { code: 'GRO_04', label: 'Butcher, Fishmonger & Deli' },
      GRO_05: { code: 'GRO_05', label: 'Bakery & Confectionery' },
      GRO_06: { code: 'GRO_06', label: 'Market & Farm Shop' },
      GRO_07: { code: 'GRO_07', label: 'Drinks & Beverages' },
      GRO_08: { code: 'GRO_08', label: 'Tobacco & Vaping' },
      GRO_09: { code: 'GRO_09', label: 'Pharmacy / Chemist (OTC)' },
      GRO_10: { code: 'GRO_10', label: 'Drugstore & Personal Care' },
    },
  },
  EAT: {
    code: 'EAT',
    label: 'Eating Out & Food Delivery',
    subcategories: {
      EAT_01: { code: 'EAT_01', label: 'Restaurant' },
      EAT_02: { code: 'EAT_02', label: 'Fast Food' },
      EAT_03: { code: 'EAT_03', label: 'Café & Coffee Shop' },
      EAT_04: { code: 'EAT_04', label: 'Bar, Pub & Club' },
      EAT_05: { code: 'EAT_05', label: 'Food Delivery & Takeaway' },
      EAT_06: { code: 'EAT_06', label: 'Street Food & Markets' },
      EAT_07: { code: 'EAT_07', label: 'Work Canteen' },
    },
  },
  TRN: {
    code: 'TRN',
    label: 'Transport & Mobility',
    subcategories: {
      TRN_01: { code: 'TRN_01', label: 'Fuel & Petrol' },
      TRN_02: { code: 'TRN_02', label: 'Vehicle Insurance' },
      TRN_03: { code: 'TRN_03', label: 'Vehicle Tax & Registration' },
      TRN_04: { code: 'TRN_04', label: 'Vehicle Servicing & Repairs' },
      TRN_05: { code: 'TRN_05', label: 'Parking & Tolls' },
      TRN_06: { code: 'TRN_06', label: 'Vehicle Purchase & Leasing' },
      TRN_07: { code: 'TRN_07', label: 'Public Transport' },
      TRN_08: { code: 'TRN_08', label: 'Train & Intercity Rail' },
      TRN_09: { code: 'TRN_09', label: 'Taxi & Rideshare' },
      TRN_10: { code: 'TRN_10', label: 'Cycling & Micro-mobility' },
      TRN_11: { code: 'TRN_11', label: 'Car Rental & Car Share' },
      TRN_12: { code: 'TRN_12', label: 'Ferry & Water Transport' },
    },
  },
  TRV: {
    code: 'TRV',
    label: 'Travel & Accommodation',
    subcategories: {
      TRV_01: { code: 'TRV_01', label: 'Flights' },
      TRV_02: { code: 'TRV_02', label: 'Hotels & Guest Houses' },
      TRV_03: { code: 'TRV_03', label: 'Vacation Rentals' },
      TRV_04: { code: 'TRV_04', label: 'Package Holidays' },
      TRV_05: { code: 'TRV_05', label: 'Car Hire' },
      TRV_06: { code: 'TRV_06', label: 'Travel Insurance' },
      TRV_07: { code: 'TRV_07', label: 'Airport & Travel Extras' },
      TRV_08: { code: 'TRV_08', label: 'Visa & Travel Documents' },
      TRV_09: { code: 'TRV_09', label: 'Currency Exchange' },
      TRV_10: { code: 'TRV_10', label: 'Activities & Excursions' },
      TRV_11: { code: 'TRV_11', label: 'Camping & Outdoors' },
    },
  },
  SHP: {
    code: 'SHP',
    label: 'Shopping & Retail',
    subcategories: {
      SHP_01: { code: 'SHP_01', label: 'Clothing & Footwear' },
      SHP_02: { code: 'SHP_02', label: 'Consumer Electronics' },
      SHP_03: { code: 'SHP_03', label: 'Books, Music & Media' },
      SHP_04: { code: 'SHP_04', label: 'Sports & Outdoor Equipment' },
      SHP_05: { code: 'SHP_05', label: 'Toys & Games' },
      SHP_06: { code: 'SHP_06', label: 'Jewellery & Accessories' },
      SHP_07: { code: 'SHP_07', label: 'General Online Shopping' },
      SHP_08: { code: 'SHP_08', label: 'Department Store' },
      SHP_09: { code: 'SHP_09', label: 'Second-Hand & Resale' },
      SHP_10: { code: 'SHP_10', label: 'Gifts & Flowers' },
      SHP_11: { code: 'SHP_11', label: 'Luxury & Designer' },
      SHP_12: { code: 'SHP_12', label: 'Baby & Infant Products' },
    },
  },
  HLT: {
    code: 'HLT',
    label: 'Health & Medical',
    subcategories: {
      HLT_01: { code: 'HLT_01', label: 'Doctor & GP' },
      HLT_02: { code: 'HLT_02', label: 'Hospital & Emergency' },
      HLT_03: { code: 'HLT_03', label: 'Dentist' },
      HLT_04: { code: 'HLT_04', label: 'Optician & Eyewear' },
      HLT_05: { code: 'HLT_05', label: 'Pharmacy (prescription)' },
      HLT_06: { code: 'HLT_06', label: 'Mental Health & Therapy' },
      HLT_07: { code: 'HLT_07', label: 'Alternative Medicine' },
      HLT_08: { code: 'HLT_08', label: 'Medical Equipment' },
      HLT_09: { code: 'HLT_09', label: 'Fitness & Gym' },
      HLT_10: { code: 'HLT_10', label: 'Wellness & Spa' },
      HLT_11: { code: 'HLT_11', label: 'Health Insurance' },
    },
  },
  EDU: {
    code: 'EDU',
    label: 'Education',
    subcategories: {
      EDU_01: { code: 'EDU_01', label: 'School Fees & Tuition' },
      EDU_02: { code: 'EDU_02', label: 'University & College' },
      EDU_03: { code: 'EDU_03', label: 'Online Courses' },
      EDU_04: { code: 'EDU_04', label: 'Books & Study Materials' },
      EDU_05: { code: 'EDU_05', label: 'Training & Workshops' },
      EDU_06: { code: 'EDU_06', label: 'Stationery & Supplies' },
      EDU_07: { code: 'EDU_07', label: 'Childcare & Nursery' },
      EDU_08: { code: 'EDU_08', label: 'Extracurricular & Tutoring' },
    },
  },
  ENT: {
    code: 'ENT',
    label: 'Entertainment & Leisure',
    subcategories: {
      ENT_01: { code: 'ENT_01', label: 'Streaming & Digital Subscriptions' },
      ENT_02: { code: 'ENT_02', label: 'Cinema & Theatre' },
      ENT_03: { code: 'ENT_03', label: 'Concerts & Live Events' },
      ENT_04: { code: 'ENT_04', label: 'Sports Events' },
      ENT_05: { code: 'ENT_05', label: 'Video Games & Gaming' },
      ENT_06: { code: 'ENT_06', label: 'Hobbies & Crafts' },
      ENT_07: { code: 'ENT_07', label: 'Newspapers & Magazines' },
      ENT_08: { code: 'ENT_08', label: 'Gambling & Betting' },
      ENT_09: { code: 'ENT_09', label: 'Nightlife & Clubs' },
      ENT_10: { code: 'ENT_10', label: 'Amusement Parks & Attractions' },
      ENT_11: { code: 'ENT_11', label: 'Photography & Art' },
    },
  },
  COM: {
    code: 'COM',
    label: 'Communications & Subscriptions',
    subcategories: {
      COM_01: { code: 'COM_01', label: 'Mobile Phone & Plan' },
      COM_02: { code: 'COM_02', label: 'Software & App Subscriptions' },
      COM_03: { code: 'COM_03', label: 'Cloud Storage & Hosting' },
      COM_04: { code: 'COM_04', label: 'Postal & Courier' },
      COM_05: { code: 'COM_05', label: 'Memberships & Clubs' },
      COM_06: { code: 'COM_06', label: 'Marketing & Advertising' },
    },
  },
  FIN: {
    code: 'FIN',
    label: 'Insurance & Finance',
    subcategories: {
      FIN_01: { code: 'FIN_01', label: 'Life Insurance' },
      FIN_02: { code: 'FIN_02', label: 'Home & Contents Insurance' },
      FIN_03: { code: 'FIN_03', label: 'Income Protection' },
      FIN_04: { code: 'FIN_04', label: 'Legal & Other Insurance' },
      FIN_05: { code: 'FIN_05', label: 'Bank Fees' },
      FIN_06: { code: 'FIN_06', label: 'Credit Card Fees & Interest' },
      FIN_07: { code: 'FIN_07', label: 'Loan Repayments' },
      FIN_08: { code: 'FIN_08', label: 'Investment & Brokerage' },
      FIN_09: { code: 'FIN_09', label: 'Pension Contributions' },
      FIN_10: { code: 'FIN_10', label: 'Crypto & Digital Assets' },
      FIN_11: { code: 'FIN_11', label: 'Savings Transfers' },
      FIN_12: { code: 'FIN_12', label: 'Foreign Exchange & Remittance' },
      FIN_13: { code: 'FIN_13', label: 'Overdraft & Late Fees' },
    },
  },
  FAM: {
    code: 'FAM',
    label: 'Family & Personal Care',
    subcategories: {
      FAM_01: { code: 'FAM_01', label: 'Haircut & Barber' },
      FAM_02: { code: 'FAM_02', label: 'Beauty & Nail Salon' },
      FAM_03: { code: 'FAM_03', label: "Children's Activities" },
      FAM_04: { code: 'FAM_04', label: 'Child Maintenance & Alimony' },
      FAM_05: { code: 'FAM_05', label: 'Pet Food & Supplies' },
      FAM_06: { code: 'FAM_06', label: 'Vet & Pet Care' },
      FAM_07: { code: 'FAM_07', label: 'Laundry & Dry Cleaning' },
      FAM_08: { code: 'FAM_08', label: 'Weddings & Ceremonies' },
    },
  },
  GOV: {
    code: 'GOV',
    label: 'Taxes, Government & Legal',
    subcategories: {
      GOV_01: { code: 'GOV_01', label: 'Income Tax' },
      GOV_02: { code: 'GOV_02', label: 'Sales / VAT Tax' },
      GOV_03: { code: 'GOV_03', label: 'Property Tax' },
      GOV_04: { code: 'GOV_04', label: 'Vehicle Tax' },
      GOV_05: { code: 'GOV_05', label: 'Business Tax' },
      GOV_06: { code: 'GOV_06', label: 'Fines & Penalties' },
      GOV_07: { code: 'GOV_07', label: 'Legal & Accounting Fees' },
      GOV_08: { code: 'GOV_08', label: 'Licences & Permits' },
    },
  },
  SOC: {
    code: 'SOC',
    label: 'Charities & Social',
    subcategories: {
      SOC_01: { code: 'SOC_01', label: 'Charitable Donations' },
      SOC_02: { code: 'SOC_02', label: 'Religious Contributions' },
      SOC_03: { code: 'SOC_03', label: 'Union & Professional Membership' },
      SOC_04: { code: 'SOC_04', label: 'Community & Social Clubs' },
      SOC_05: { code: 'SOC_05', label: 'Funeral & Burial' },
      SOC_06: { code: 'SOC_06', label: 'Informal Support & Remittance' },
    },
  },
  TFR: {
    code: 'TFR',
    label: 'Transfers & Uncategorised',
    subcategories: {
      TFR_01: { code: 'TFR_01', label: 'Cash Withdrawal' },
      TFR_02: { code: 'TFR_02', label: 'Internal Transfer' },
      TFR_03: { code: 'TFR_03', label: 'P2P Transfer' },
      TFR_04: { code: 'TFR_04', label: 'Refund & Chargeback' },
      TFR_05: { code: 'TFR_05', label: 'Uncategorised' },
    },
  },
}

export const ALL_CATEGORIES: Record<ParentCategoryCode, ParentCategory> = {
  ...INCOME_CATEGORIES,
  ...EXPENSE_CATEGORIES,
}
