import type { Transaction } from '@/types'

export const DEMO_TRANSACTIONS: Transaction[] = [
  // January 2026
  {
    date: '2026-01-02',
    description: 'Apartment Rent - January',
    value: '-850.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_01',
  },
  {
    date: '2026-01-03',
    description: 'Workshop Rent - January',
    value: '-1150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_02',
  },
  {
    date: '2026-01-05',
    description: 'Health Insurance - January',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_04',
  },
  {
    date: '2026-01-06',
    description: 'Groceries - REWE',
    value: '-127.35',
    currency: 'EUR',
    extra: null,
    category: 'GRO_01',
  },
  {
    date: '2026-01-08',
    description: 'Client Payment - Custom Kitchen Cabinets',
    value: '4200.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-01-10',
    description: 'Wood & Materials - Supplier',
    value: '-1850.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_01',
  },
  {
    date: '2026-01-12',
    description: 'Home Utilities - Electricity & Gas',
    value: '-185.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_02',
  },
  {
    date: '2026-01-18',
    description: 'Client Payment - Wooden Dining Table',
    value: '2800.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-01-22',
    description: 'Vehicle Fuel',
    value: '-115.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_01',
  },
  {
    date: '2026-01-28',
    description: 'Client Payment - Bookshelves Installation',
    value: '1500.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },

  // February 2026
  {
    date: '2026-02-01',
    description: 'Apartment Rent - February',
    value: '-850.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_01',
  },
  {
    date: '2026-02-02',
    description: 'Workshop Rent - February',
    value: '-1150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_02',
  },
  {
    date: '2026-02-03',
    description: 'Health Insurance - February',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_04',
  },
  {
    date: '2026-02-05',
    description: 'Client Payment - Office Renovation',
    value: '6500.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-02-07',
    description: 'Groceries - Aldi',
    value: '-86.45',
    currency: 'EUR',
    extra: null,
    category: 'GRO_01',
  },
  {
    date: '2026-02-08',
    description: 'Timber & Plywood - Large Order',
    value: '-2400.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_01',
  },
  {
    date: '2026-02-10',
    description: 'Liability Insurance - Quarterly',
    value: '-380.00',
    currency: 'EUR',
    extra: null,
    category: 'FIN_03',
  },
  {
    date: '2026-02-15',
    description: 'Vehicle Service & MOT',
    value: '-420.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_03',
  },
  {
    date: '2026-02-18',
    description: 'Client Payment - Custom Wardrobe',
    value: '3800.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-02-22',
    description: 'Dinner - Restaurant',
    value: '-62.50',
    currency: 'EUR',
    extra: null,
    category: 'GRO_02',
  },
  {
    date: '2026-02-25',
    description: 'Vehicle Fuel',
    value: '-110.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_01',
  },

  // March 2026
  {
    date: '2026-03-01',
    description: 'Apartment Rent - March',
    value: '-850.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_01',
  },
  {
    date: '2026-03-02',
    description: 'Workshop Rent - March',
    value: '-1150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_02',
  },
  {
    date: '2026-03-03',
    description: 'Health Insurance - March',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_04',
  },
  {
    date: '2026-03-05',
    description: 'Client Payment - Home Office Built-ins',
    value: '4800.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-03-07',
    description: 'Groceries - EDEKA',
    value: '-105.90',
    currency: 'EUR',
    extra: null,
    category: 'GRO_01',
  },
  {
    date: '2026-03-10',
    description: 'Hardwood & Oak Materials',
    value: '-1650.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_01',
  },
  {
    date: '2026-03-12',
    description: 'Workshop Utilities - Electricity & Heating',
    value: '-265.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_02',
  },
  {
    date: '2026-03-15',
    description: 'Client Payment - Kitchen Island',
    value: '3200.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-03-16',
    description: 'Internet & Phone',
    value: '-55.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_03',
  },
  {
    date: '2026-03-18',
    description: 'Vehicle Fuel',
    value: '-125.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_01',
  },
  {
    date: '2026-03-24',
    description: 'Gym Membership',
    value: '-35.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_03',
  },

  // April 2026
  {
    date: '2026-04-01',
    description: 'Apartment Rent - April',
    value: '-850.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_01',
  },
  {
    date: '2026-04-02',
    description: 'Workshop Rent - April',
    value: '-1150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_02',
  },
  {
    date: '2026-04-03',
    description: 'Health Insurance - April',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_04',
  },
  {
    date: '2026-04-05',
    description: 'Client Payment - Commercial Shopfitting',
    value: '9500.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-04-07',
    description: 'Groceries - REWE',
    value: '-134.75',
    currency: 'EUR',
    extra: null,
    category: 'GRO_01',
  },
  {
    date: '2026-04-08',
    description: 'Premium Wood Materials - Bulk Order',
    value: '-3500.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_01',
  },
  {
    date: '2026-04-10',
    description: 'Vehicle Insurance - Semi-Annual',
    value: '-580.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_02',
  },
  {
    date: '2026-04-15',
    description: 'Accounting & Bookkeeping',
    value: '-180.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_05',
  },
  {
    date: '2026-04-22',
    description: 'Vehicle Fuel',
    value: '-135.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_01',
  },
  {
    date: '2026-04-25',
    description: 'Netflix & Spotify',
    value: '-25.00',
    currency: 'EUR',
    extra: null,
    category: 'FAM_05',
  },
  {
    date: '2026-04-26',
    description: 'Takeaway - Lieferando',
    value: '-28.90',
    currency: 'EUR',
    extra: null,
    category: 'GRO_02',
  },
  {
    date: '2026-04-30',
    description: 'Bank Fees',
    value: '-14.90',
    currency: 'EUR',
    extra: null,
    category: 'FIN_05',
  },

  // May 2026
  {
    date: '2026-05-01',
    description: 'Apartment Rent - May',
    value: '-850.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_01',
  },
  {
    date: '2026-05-02',
    description: 'Workshop Rent - May',
    value: '-1150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_02',
  },
  {
    date: '2026-05-03',
    description: 'Health Insurance - May',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_04',
  },
  {
    date: '2026-05-06',
    description: 'Client Payment - Staircase Renovation',
    value: '7200.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-05-08',
    description: 'Groceries - REWE',
    value: '-118.40',
    currency: 'EUR',
    extra: null,
    category: 'GRO_01',
  },
  {
    date: '2026-05-10',
    description: 'Specialized Wood & Veneers',
    value: '-2100.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_01',
  },
  {
    date: '2026-05-12',
    description: 'Liability Insurance - Quarterly',
    value: '-380.00',
    currency: 'EUR',
    extra: null,
    category: 'FIN_03',
  },
  {
    date: '2026-05-15',
    description: 'Client Payment - Outdoor Furniture',
    value: '3800.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-05-18',
    description: 'Vehicle Fuel',
    value: '-120.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_01',
  },
  {
    date: '2026-05-20',
    description: 'Marketing - Website Hosting & Update',
    value: '-150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_04',
  },
  {
    date: '2026-05-22',
    description: 'Winter Jacket - H&M',
    value: '-89.95',
    currency: 'EUR',
    extra: null,
    category: 'FAM_03',
  },
  {
    date: '2026-05-28',
    description: 'Vehicle Service',
    value: '-200.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_03',
  },

  // June 2026
  {
    date: '2026-06-01',
    description: 'Apartment Rent - June',
    value: '-850.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_01',
  },
  {
    date: '2026-06-02',
    description: 'Workshop Rent - June',
    value: '-1150.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_02',
  },
  {
    date: '2026-06-03',
    description: 'Health Insurance - June',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HLT_04',
  },
  {
    date: '2026-06-05',
    description: 'Client Payment - Restaurant Interior',
    value: '11500.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-06-07',
    description: 'Groceries - EDEKA',
    value: '-109.65',
    currency: 'EUR',
    extra: null,
    category: 'GRO_01',
  },
  {
    date: '2026-06-10',
    description: 'Commercial Grade Materials',
    value: '-3800.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_01',
  },
  {
    date: '2026-06-15',
    description: 'Workshop Ventilation Upgrade',
    value: '-450.00',
    currency: 'EUR',
    extra: null,
    category: 'HOU_05',
  },
  {
    date: '2026-06-18',
    description: 'Client Payment - Library Shelving',
    value: '4100.00',
    currency: 'EUR',
    extra: null,
    category: 'INC_03',
  },
  {
    date: '2026-06-20',
    description: 'Invoicing Software - Quarterly',
    value: '-135.00',
    currency: 'EUR',
    extra: null,
    category: 'BUS_03',
  },
  {
    date: '2026-06-22',
    description: 'Vehicle Fuel',
    value: '-125.00',
    currency: 'EUR',
    extra: null,
    category: 'TRN_01',
  },
  {
    date: '2026-06-28',
    description: 'Haircut',
    value: '-32.00',
    currency: 'EUR',
    extra: null,
    category: 'FAM_04',
  },
]
