import type { ParsedContentRow } from '@/types'

export const DEMO_TRANSACTIONS: ParsedContentRow[] = [
  {
    date: '2026-01-05',
    description: 'Workshop Rent - January',
    value: '-650.00',
    currency: 'EUR',
    category: 'Office & Rent',
  },
  {
    date: '2026-01-08',
    description: 'Client Payment - Custom Kitchen Cabinets',
    value: '4200.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-01-10',
    description: 'Wood & Materials - Supplier',
    value: '-850.00',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-01-12',
    description: 'Professional Insurance - Quarterly',
    value: '-280.00',
    currency: 'EUR',
    category: 'Professional Fees',
  },
  {
    date: '2026-01-15',
    description: 'Power Tools - Makita Drill Set',
    value: '-320.00',
    currency: 'EUR',
    category: 'Equipment',
  },
  {
    date: '2026-01-18',
    description: 'Client Payment - Wooden Dining Table',
    value: '2800.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-01-22',
    description: 'Vehicle Fuel - Business Trips',
    value: '-95.50',
    currency: 'EUR',
    category: 'Travel Expenses',
  },
  {
    date: '2026-01-25',
    description: 'Hardware & Fixings',
    value: '-145.80',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-01-28',
    description: 'Client Payment - Bookshelves Installation',
    value: '1500.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-02-01',
    description: 'Workshop Rent - February',
    value: '-650.00',
    currency: 'EUR',
    category: 'Office & Rent',
  },
  {
    date: '2026-02-05',
    description: 'Client Payment - Office Renovation',
    value: '6500.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-02-08',
    description: 'Timber & Plywood - Large Order',
    value: '-1250.00',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-02-12',
    description: 'Workshop Safety Equipment',
    value: '-180.00',
    currency: 'EUR',
    category: 'Equipment',
  },
  {
    date: '2026-02-15',
    description: 'Vehicle Service & Maintenance',
    value: '-220.00',
    currency: 'EUR',
    category: 'Vehicle Costs',
  },
  {
    date: '2026-02-18',
    description: 'Client Payment - Custom Wardrobe',
    value: '3800.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-02-20',
    description: 'Paint & Finishing Materials',
    value: '-165.50',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-02-22',
    description: 'Business Cards & Advertising',
    value: '-85.00',
    currency: 'EUR',
    category: 'Marketing',
  },
  {
    date: '2026-02-25',
    description: 'Vehicle Fuel - Business Trips',
    value: '-110.00',
    currency: 'EUR',
    category: 'Travel Expenses',
  },
  {
    date: '2026-02-28',
    description: 'Client Payment - Garden Deck Construction',
    value: '5200.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-03-02',
    description: 'Workshop Rent - March',
    value: '-650.00',
    currency: 'EUR',
    category: 'Office & Rent',
  },
  {
    date: '2026-03-05',
    description: 'Client Payment - Home Office Built-ins',
    value: '4800.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-03-10',
    description: 'Hardwood & Oak Materials',
    value: '-1100.00',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-03-15',
    description: 'Client Payment - Kitchen Island',
    value: '3200.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-03-20',
    description: 'Vehicle Fuel & Maintenance',
    value: '-180.00',
    currency: 'EUR',
    category: 'Travel Expenses',
  },
  {
    date: '2026-03-25',
    description: 'Client Payment - Entertainment Unit',
    value: '2900.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-04-01',
    description: 'Workshop Rent - April',
    value: '-650.00',
    currency: 'EUR',
    category: 'Office & Rent',
  },
  {
    date: '2026-04-05',
    description: 'Client Payment - Large Commercial Project',
    value: '9500.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-04-08',
    description: 'Premium Wood Materials - Bulk Order',
    value: '-1800.00',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-04-12',
    description: 'Professional Insurance - Quarterly',
    value: '-280.00',
    currency: 'EUR',
    category: 'Professional Fees',
  },
  {
    date: '2026-04-18',
    description: 'New Router & Sanding Equipment',
    value: '-520.00',
    currency: 'EUR',
    category: 'Equipment',
  },
  {
    date: '2026-04-25',
    description: 'Client Payment - Bedroom Furniture Set',
    value: '5600.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-05-01',
    description: 'Workshop Rent - May',
    value: '-650.00',
    currency: 'EUR',
    category: 'Office & Rent',
  },
  {
    date: '2026-05-06',
    description: 'Client Payment - Staircase Renovation',
    value: '7200.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-05-10',
    description: 'Specialized Wood & Veneers',
    value: '-980.50',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-05-15',
    description: 'Client Payment - Outdoor Furniture',
    value: '3800.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-05-20',
    description: 'Marketing Materials & Website',
    value: '-150.00',
    currency: 'EUR',
    category: 'Marketing',
  },
  {
    date: '2026-05-28',
    description: 'Vehicle Service',
    value: '-200.00',
    currency: 'EUR',
    category: 'Vehicle Costs',
  },
  {
    date: '2026-06-02',
    description: 'Workshop Rent - June',
    value: '-650.00',
    currency: 'EUR',
    category: 'Office & Rent',
  },
  {
    date: '2026-06-05',
    description: 'Client Payment - Restaurant Interior',
    value: '11500.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-06-10',
    description: 'Commercial Grade Materials',
    value: '-2100.00',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-06-15',
    description: 'Workshop Ventilation Upgrade',
    value: '-450.00',
    currency: 'EUR',
    category: 'Equipment',
  },
  {
    date: '2026-06-18',
    description: 'Client Payment - Library Shelving',
    value: '4100.00',
    currency: 'EUR',
    category: 'Revenue',
  },
  {
    date: '2026-06-25',
    description: 'Finishing Supplies & Hardware',
    value: '-285.00',
    currency: 'EUR',
    category: 'Materials',
  },
  {
    date: '2026-06-28',
    description: 'Vehicle Fuel - Business Trips',
    value: '-125.00',
    currency: 'EUR',
    category: 'Travel Expenses',
  },
]
