import type { PrimaryCategory } from '@/types'

export const CATEGORIES: PrimaryCategory[] = [
  {
    code: 'INC',
    label: 'Income',
    subcategories: [
      { code: 'INC-01', label: 'Salary & Wages' },
      { code: 'INC-02', label: 'Freelance & Self-Employment' },
      { code: 'INC-03', label: 'Rental Income' },
      { code: 'INC-04', label: 'Investment Income' },
      { code: 'INC-05', label: 'Capital Gains' },
      { code: 'INC-06', label: 'Government Benefits' },
      { code: 'INC-07', label: 'Pension & Retirement' },
      { code: 'INC-08', label: 'Tax Refund' },
      { code: 'INC-09', label: 'Gifts & Informal Transfers' },
      { code: 'INC-10', label: 'Business Revenue' },
      { code: 'INC-11', label: 'Side Income & Resale' },
      { code: 'INC-12', label: 'Other Income' },
    ],
  },
  {
    code: 'HOU',
    label: 'Housing & Utilities',
    subcategories: [
      { code: 'HOU-01', label: 'Rent' },
      { code: 'HOU-02', label: 'Mortgage' },
      { code: 'HOU-03', label: 'Property Rates & Municipal Fees' },
      { code: 'HOU-04', label: 'Electricity' },
      { code: 'HOU-05', label: 'Gas & Heating' },
      { code: 'HOU-06', label: 'Water & Sewage' },
      { code: 'HOU-07', label: 'Waste & Recycling' },
      { code: 'HOU-08', label: 'Home Internet & Landline' },
      { code: 'HOU-09', label: 'TV Licence & Broadcast Fees' },
      { code: 'HOU-10', label: 'Furniture & Home Furnishings' },
      { code: 'HOU-11', label: 'Home Appliances' },
      { code: 'HOU-12', label: 'Home Improvement & Renovation' },
      { code: 'HOU-13', label: 'Garden & Outdoor' },
      { code: 'HOU-14', label: 'Cleaning & Domestic Services' },
      { code: 'HOU-15', label: 'Security & Alarm Systems' },
      { code: 'HOU-16', label: 'Household Supplies & Hardware' },
      { code: 'HOU-17', label: 'Removal & Storage' },
    ],
  },
  {
    code: 'GRO',
    label: 'Groceries & Daily Essentials',
    subcategories: [
      { code: 'GRO-01', label: 'Supermarket & Grocery' },
      { code: 'GRO-02', label: 'Discount Grocery' },
      { code: 'GRO-03', label: 'Organic & Specialty Food' },
      { code: 'GRO-04', label: 'Butcher, Fishmonger & Deli' },
      { code: 'GRO-05', label: 'Bakery & Confectionery' },
      { code: 'GRO-06', label: 'Market & Farm Shop' },
      { code: 'GRO-07', label: 'Drinks & Beverages' },
      { code: 'GRO-08', label: 'Tobacco & Vaping' },
      { code: 'GRO-09', label: 'Pharmacy / Chemist (OTC)' },
      { code: 'GRO-10', label: 'Drugstore & Personal Care' },
    ],
  },
  {
    code: 'EAT',
    label: 'Eating Out & Food Delivery',
    subcategories: [
      { code: 'EAT-01', label: 'Restaurant' },
      { code: 'EAT-02', label: 'Fast Food' },
      { code: 'EAT-03', label: 'Café & Coffee Shop' },
      { code: 'EAT-04', label: 'Bar, Pub & Club' },
      { code: 'EAT-05', label: 'Food Delivery & Takeaway' },
      { code: 'EAT-06', label: 'Street Food & Markets' },
      { code: 'EAT-07', label: 'Work Canteen' },
    ],
  },
  {
    code: 'TRN',
    label: 'Transport & Mobility',
    subcategories: [
      { code: 'TRN-01', label: 'Fuel & Petrol' },
      { code: 'TRN-02', label: 'Vehicle Insurance' },
      { code: 'TRN-03', label: 'Vehicle Tax & Registration' },
      { code: 'TRN-04', label: 'Vehicle Servicing & Repairs' },
      { code: 'TRN-05', label: 'Parking & Tolls' },
      { code: 'TRN-06', label: 'Vehicle Purchase & Leasing' },
      { code: 'TRN-07', label: 'Public Transport' },
      { code: 'TRN-08', label: 'Train & Intercity Rail' },
      { code: 'TRN-09', label: 'Taxi & Rideshare' },
      { code: 'TRN-10', label: 'Cycling & Micro-mobility' },
      { code: 'TRN-11', label: 'Car Rental & Car Share' },
      { code: 'TRN-12', label: 'Ferry & Water Transport' },
    ],
  },
  {
    code: 'TRV',
    label: 'Travel & Accommodation',
    subcategories: [
      { code: 'TRV-01', label: 'Flights' },
      { code: 'TRV-02', label: 'Hotels & Guest Houses' },
      { code: 'TRV-03', label: 'Vacation Rentals' },
      { code: 'TRV-04', label: 'Package Holidays' },
      { code: 'TRV-05', label: 'Car Hire' },
      { code: 'TRV-06', label: 'Travel Insurance' },
      { code: 'TRV-07', label: 'Airport & Travel Extras' },
      { code: 'TRV-08', label: 'Visa & Travel Documents' },
      { code: 'TRV-09', label: 'Currency Exchange' },
      { code: 'TRV-10', label: 'Activities & Excursions' },
      { code: 'TRV-11', label: 'Camping & Outdoors' },
    ],
  },
  {
    code: 'SHP',
    label: 'Shopping & Retail',
    subcategories: [
      { code: 'SHP-01', label: 'Clothing & Footwear' },
      { code: 'SHP-02', label: 'Consumer Electronics' },
      { code: 'SHP-03', label: 'Books, Music & Media' },
      { code: 'SHP-04', label: 'Sports & Outdoor Equipment' },
      { code: 'SHP-05', label: 'Toys & Games' },
      { code: 'SHP-06', label: 'Jewellery & Accessories' },
      { code: 'SHP-07', label: 'General Online Shopping' },
      { code: 'SHP-08', label: 'Department Store' },
      { code: 'SHP-09', label: 'Second-Hand & Resale' },
      { code: 'SHP-10', label: 'Gifts & Flowers' },
      { code: 'SHP-11', label: 'Luxury & Designer' },
      { code: 'SHP-12', label: 'Baby & Infant Products' },
    ],
  },
  {
    code: 'HLT',
    label: 'Health & Medical',
    subcategories: [
      { code: 'HLT-01', label: 'Doctor & GP' },
      { code: 'HLT-02', label: 'Hospital & Emergency' },
      { code: 'HLT-03', label: 'Dentist' },
      { code: 'HLT-04', label: 'Optician & Eyewear' },
      { code: 'HLT-05', label: 'Pharmacy (prescription)' },
      { code: 'HLT-06', label: 'Mental Health & Therapy' },
      { code: 'HLT-07', label: 'Alternative Medicine' },
      { code: 'HLT-08', label: 'Medical Equipment' },
      { code: 'HLT-09', label: 'Fitness & Gym' },
      { code: 'HLT-10', label: 'Wellness & Spa' },
      { code: 'HLT-11', label: 'Health Insurance' },
    ],
  },
  {
    code: 'EDU',
    label: 'Education',
    subcategories: [
      { code: 'EDU-01', label: 'School Fees & Tuition' },
      { code: 'EDU-02', label: 'University & College' },
      { code: 'EDU-03', label: 'Online Courses' },
      { code: 'EDU-04', label: 'Books & Study Materials' },
      { code: 'EDU-05', label: 'Training & Workshops' },
      { code: 'EDU-06', label: 'Stationery & Supplies' },
      { code: 'EDU-07', label: 'Childcare & Nursery' },
      { code: 'EDU-08', label: 'Extracurricular & Tutoring' },
    ],
  },
  {
    code: 'ENT',
    label: 'Entertainment & Leisure',
    subcategories: [
      { code: 'ENT-01', label: 'Streaming & Digital Subscriptions' },
      { code: 'ENT-02', label: 'Cinema & Theatre' },
      { code: 'ENT-03', label: 'Concerts & Live Events' },
      { code: 'ENT-04', label: 'Sports Events' },
      { code: 'ENT-05', label: 'Video Games & Gaming' },
      { code: 'ENT-06', label: 'Hobbies & Crafts' },
      { code: 'ENT-07', label: 'Newspapers & Magazines' },
      { code: 'ENT-08', label: 'Gambling & Betting' },
      { code: 'ENT-09', label: 'Nightlife & Clubs' },
      { code: 'ENT-10', label: 'Amusement Parks & Attractions' },
      { code: 'ENT-11', label: 'Photography & Art' },
    ],
  },
  {
    code: 'COM',
    label: 'Communications & Subscriptions',
    subcategories: [
      { code: 'COM-01', label: 'Mobile Phone & Plan' },
      { code: 'COM-02', label: 'Software & App Subscriptions' },
      { code: 'COM-03', label: 'Cloud Storage & Hosting' },
      { code: 'COM-04', label: 'Postal & Courier' },
      { code: 'COM-05', label: 'Memberships & Clubs' },
    ],
  },
  {
    code: 'FIN',
    label: 'Insurance & Finance',
    subcategories: [
      { code: 'FIN-01', label: 'Life Insurance' },
      { code: 'FIN-02', label: 'Home & Contents Insurance' },
      { code: 'FIN-03', label: 'Income Protection' },
      { code: 'FIN-04', label: 'Legal & Other Insurance' },
      { code: 'FIN-05', label: 'Bank Fees' },
      { code: 'FIN-06', label: 'Credit Card Fees & Interest' },
      { code: 'FIN-07', label: 'Loan Repayments' },
      { code: 'FIN-08', label: 'Investment & Brokerage' },
      { code: 'FIN-09', label: 'Pension Contributions' },
      { code: 'FIN-10', label: 'Crypto & Digital Assets' },
      { code: 'FIN-11', label: 'Savings Transfers' },
      { code: 'FIN-12', label: 'Foreign Exchange & Remittance' },
      { code: 'FIN-13', label: 'Overdraft & Late Fees' },
    ],
  },
  {
    code: 'FAM',
    label: 'Family & Personal Care',
    subcategories: [
      { code: 'FAM-01', label: 'Haircut & Barber' },
      { code: 'FAM-02', label: 'Beauty & Nail Salon' },
      { code: 'FAM-03', label: "Children's Activities" },
      { code: 'FAM-04', label: 'Child Maintenance & Alimony' },
      { code: 'FAM-05', label: 'Pet Food & Supplies' },
      { code: 'FAM-06', label: 'Vet & Pet Care' },
      { code: 'FAM-07', label: 'Laundry & Dry Cleaning' },
      { code: 'FAM-08', label: 'Weddings & Ceremonies' },
    ],
  },
  {
    code: 'GOV',
    label: 'Taxes, Government & Legal',
    subcategories: [
      { code: 'GOV-01', label: 'Income Tax' },
      { code: 'GOV-02', label: 'Sales / VAT Tax' },
      { code: 'GOV-03', label: 'Property Tax' },
      { code: 'GOV-04', label: 'Vehicle Tax' },
      { code: 'GOV-05', label: 'Business Tax' },
      { code: 'GOV-06', label: 'Fines & Penalties' },
      { code: 'GOV-07', label: 'Legal & Accounting Fees' },
      { code: 'GOV-08', label: 'Licences & Permits' },
    ],
  },
  {
    code: 'SOC',
    label: 'Charities & Social',
    subcategories: [
      { code: 'SOC-01', label: 'Charitable Donations' },
      { code: 'SOC-02', label: 'Religious Contributions' },
      { code: 'SOC-03', label: 'Union & Professional Membership' },
      { code: 'SOC-04', label: 'Community & Social Clubs' },
      { code: 'SOC-05', label: 'Funeral & Burial' },
      { code: 'SOC-06', label: 'Informal Support & Remittance' },
    ],
  },
  {
    code: 'TFR',
    label: 'Transfers & Uncategorised',
    subcategories: [
      { code: 'TFR-01', label: 'Cash Withdrawal' },
      { code: 'TFR-02', label: 'Internal Transfer' },
      { code: 'TFR-03', label: 'P2P Transfer' },
      { code: 'TFR-04', label: 'Refund & Chargeback' },
      { code: 'TFR-05', label: 'Uncategorised' },
    ],
  },
]
